language: julia
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - gfortran
  homebrew:
    packages:
      - gfortran
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999
matrix:
  allow_failures:
  - julia: nightly
# before_install:
#   - if [ `uname` = "Linux" ]; then
#       sudo apt-get install gfortran -y;
#     elif [ `uname` = "Darwin" ]; then
#       brew install gcc;
#     fi
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("Lasso"); Pkg.test("Lasso"; coverage=true)'
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Lasso")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
